### ISSUE TITLE
[Example request] Hi, is there any example?

### ISSUE THREAD

**Issue by emisjerry** [tnichols217/obsidian-columns#1]
Hi,

Where can find an example? Thanks.

**Comment by tnichols217** [comment]
Added examples to README
Commit a020f0b8570921c30c06052c779f81b14490045a

**Comment by emisjerry** [comment]
Thanks. i'll try it.

**Comment by emisjerry** [comment]
What i've tested as below. The last codeblock seems abnormal. Lists in column-2 don't indent.

![image](https://user-images.githubusercontent.com/131511/165654943-007ff369-5474-4ae9-8c80-42a582767833.png)

<pre>
```col
Column 1-1
Column 1-2

- column 2-1
	1. Item 1
	1. Item 2
	1. Item 3
- column 2-2
- column 2-3

> [!INFO] Callouts
>  column 3-1
>  column 3-2
>> [!ERROR] Error description
>>  Nested callout

```js
  let msg = "Hello, world!";
  let url = window.location.href;
```
```
</pre>

**Comment by tnichols217** [comment]
when using recursive codeblocks, dont forget to add an extra tick to the containing codeblock :)

like in my example above, the col codeblock uses 4 ticks while the inside ones use 3.

**Comment by tnichols217** [comment]
`````md
````col
Column 1-1
Column 1-2

- column 2-1
	1. Item 1
	1. Item 2
	1. Item 3
- column 2-2
- column 2-3

> [!INFO] Callouts
>  column 3-1
>  column 3-2
>> [!ERROR] Error description
>>  Nested callout

```js
  let msg = "Hello, world!";
  let url = window.location.href;
```
````
`````

**Comment by emisjerry** [comment]
I've found that Database folder plugin (https://github.com/RafaelGB/obsidian-bd-folder) caused the unindented lists.
Thanks.

**Comment by emisjerry** [comment]
Yes. I'll make a video to promote your plugin when i'm available. Thanks.

**Comment by tnichols217** [comment]
Thanks!
