### ISSUE TITLE
dataview plugin support

### ISSUE THREAD

**Issue by imeed166** [tnichols217/obsidian-columns#10]
# [Describe your issue]
dataview query is not rendered in the column

## Steps to reproduce:
paste this and add the current file path
`````
- [ ] Task
````col
```col-md
text
```
```dataview
task from "current file path"
```
````
`````
## System Info
OS: MACOS 12.1
Obsidian Version: 0.14.6
Plugin Version: 1.0.7

**Comment by tnichols217** [comment]
I have looked around and cant find what is causing this bug. Ill be working on it though

**Comment by tnichols217** [comment]
Fixed in commit b7bf94060436225b217dcc5cde957de0156f46b2 live in version [1.0.8](https://github.com/tnichols217/obsidian-columns/tree/1.0.8)

**Comment by johans3** [comment]
For callouts i used successfully:
````
> [! abstract] 
> ## title
> ```dataview
> list from "path/to/directory" 
> ```
````
For admonition, i used successfully :
`````
````ad-note
##title
```dataview
list from "path/to/directory" 
```
````
`````
But if i add one of these code blocks inside
````
```col
```
````
No matter how much ticks I add to nest dataview blocks properly, **Obsidian Columns** fails to load the dataview query. So the bug isn't in callouts / admonition 
Could you investigate this bug, please?

**Comment by imeed166** [comment]
I have found another problem with dataview and callouts : When embedding a dataview query into a callout that is collapsed by default, in reading view the callout won't expand.

Here is what I'm using :
`````
````col
> [!info]-
> text

> [!info]-
>```dataview
>task from "to clean/testing.md"
>```
````
`````
And this is what happens :

https://user-images.githubusercontent.com/38974541/167168887-620f301f-486e-47ed-8cc8-36d3126b6862.mov

**Comment by tnichols217** [comment]
@imeed166 are you on the latest version or not?

**Comment by imeed166** [comment]
yes, 1.0.8

**Comment by tnichols217** [comment]
Just tested, latest version of the plugin has functioning dropdowns
https://user-images.githubusercontent.com/62992267/167172473-35773785-f13f-427d-8284-7e9219705532.mp4

**Comment by imeed166** [comment]
I tried everything in a clean vault, I found that It works normally with dataview stable version (0.4.26), But when I use the beta version of dataview (0.5.18), the callout don't expand in reading view. 

Just so you know, the callout with the dataview (beta) query expands normally in reading view if it's not in a column.

**Comment by tnichols217** [comment]
Ah, I see I'll go and see what the deal is also I'm available on discord if you'd like to communicate easier at pmis#5937

**Comment by zmactep** [comment]
Hi!

Thank you for a plugin. I have troubles with dataview integration too. Any dataview block in columns just is not showed.

I have obsidian v0.15.9 and columns plugin v1.2.0

**Comment by RenanSantos7** [comment]
Firstly, thank you for your plugin. I have problems with Obsidian Columns and Dataview to.

My code:
``````col
```col-md
flex-grow=1
===
## Leituras atuais
```dataview
list
from "Experiências/Livros que li"
where statusLeitura="Lendo"
```

```

```col-md
flex-grow=1
===
## Abandonados
```dataview
list
where statusLeitura="Abandonado"
```

```
``````
**Result in Live Preview:**
![Captura de tela 2023-04-26 083825](https://user-images.githubusercontent.com/36091929/234563645-f33b8328-5639-463b-9393-c02722f61a17.png)

**Result in Reading mode**
![Captura de tela 2023-04-26 083825](https://user-images.githubusercontent.com/36091929/234563813-581dcdad-4b7c-4bb1-b6ed-365e6cedc25d.png)
