### ISSUE TITLE
Padding between column blocks

### ISSUE THREAD

**Issue by johans3** [tnichols217/obsidian-columns#12]
# [Describe your issue]
The padding **between columns blocks** is too big in `preview mode`. The same padding looks totally fine in `life preview`. Please see attachment (review mode, padding in orange) 
![Clmn-padd_114438](https://user-images.githubusercontent.com/48620536/167248916-68278935-888a-49f6-a614-a24df37cd594.jpg)

## Steps to reproduce:
````col
```ad-note
title: note 1
```
```ad-note
title: note 2
```
````
````col
```ad-note
title: note 1
```
```ad-note
title: note 2
```
````
## System Info
OS: Mac OSx
Obsidian Version: 0.14.6 
Plugin Version: 1.0.8

**Comment by tnichols217** [comment]
Oh yeah, this is a problem due to margin collapsing. Margins normally collapse between multiple elements, however since im using flexbox to create columns, margin collapse does not work properly. I will implement some css to fix this though
