### ISSUE TITLE
Flex Growth within the column markdown

### ISSUE THREAD

**Issue by BeeGass** [tnichols217/obsidian-columns#13]
# [Describe your issue]
[short description]
its not immediately intuitive, if its available, on how to use the flex-growth feature that is present in the use of the list syntax but within the syntax that uses `col-md` code blocks. Im hoping that documentation can be updated to address this or that if its not a feature that it could be a feature I could request.

I currently am trying to use callouts while using the flex growth, the list syntax makes it impossible to use so being able to use the code blocks equivalent would be much appreciated. 

## Steps to reproduce:
[list steps to reproduce issue]

im trying to perform this 

**First code block**
```md
- !!!col
	- 2
		description description description description description description description description description description description description description description description description description description description description description description description description 
	- 1
		>> [!navigation]+
                >> `fas:AngleLeft` [[|prev]] | [[|up]] | [[|next]] `fas:AngleRight`
                >
                >> [!content]-
                >> [TOC]
                >
                >> [!collection]-
                >> - Xcollection:: [[|Example Collection]] 
                >> - Ycollection:: [[|Example Collection]] 
                >> - Zcollection:: [[|Example Collection]] 
                >
                >> [!link]-
                >> - Link to other notes 
                >> 	- [[Example-Note]] 
                >
                >> [!tag]-
                >> - Link to MOCs and Indices
                >> 	- [[|Example-MOC]]  
                >> 	- [[|Index-Example]]
                >
                >> [!metadata]-
                >> - prev:: 
                >> - up:: 
                >> - next:: 
```

however this is not possible based off the inability to tab over a callout. It would be great to be able to do this:

**Second code block**
```md
''''col

'''col-md
flex-growth: 2

description description description description description description description description description description description description description description description description description description description description description description description description
'''

'''col-md
flex-growth: 1

>> [!navigation]+
>> `fas:AngleLeft` [[|prev]] | [[|up]] | [[|next]] `fas:AngleRight`
>
>> [!content]-
>> [TOC]
>
>> [!collection]-
>> - Xcollection:: [[|Example Collection]] 
>> - Ycollection:: [[|Example Collection]] 
>> - Zcollection:: [[|Example Collection]] 
>
>> [!link]-
>> - Link to other notes 
>> 	- [[Example-Note]] 
>
>> [!tag]-
>> - Link to MOCs and Indices
>> 	- [[|Example-MOC]]  
>> 	- [[|Index-Example]]
>
>> [!metadata]-
>> - prev:: 
>> - up:: 
>> - next:: 
'''
''''
```

note im using single quotes here to display the thought.

## System Info
OS: `ubuntu 20.06`
Obsidian Version: `v0.14.6`
Plugin Version: `v1.0.9`

**Comment by BeeGass** [comment]
realized that once I pasted in the first code block that this produced the intended result but the ability to have live preview and have the code be significantly cleaner through the use of `col-md` blocks would be much appreciated.

**Comment by tnichols217** [comment]
Ah yea, this is a thing I'm working on, adding custom flex grow for the code lock (if you read the bottom of the README.md) I'll be working on it

**Comment by tnichols217** [comment]
And also, yes the list syntax is not supported on live preview but the codeblocks are

**Comment by tnichols217** [comment]
Fixed in v1.1.0, commit d7ac20421599b42e73d55e08af403742bdf6f585

**Comment by BeeGass** [comment]
beautiful. Thanks for doing it so quickly too. Honestly pretty impressive plugin that works smoothly and the fact you are fixing things quickly. Its awesome

**Comment by tnichols217** [comment]
No problem! Im glad you enjoy my plugin!
