### ISSUE TITLE
V1.1.1 version update fails

### ISSUE THREAD

**Issue by AndyBold** [tnichols217/obsidian-columns#14]
# Updating to v1.1.1 via Obsidian is failing.

I suspect that this is related to the manifest specifying `1.1.1` and the actual release being tagged with `1.1.01` - note the errant zero.

I considering making a PR for the manifest but a better way to deal with this might be to handle the errant zero in the release version number.

## Steps to reproduce:
Try to update the plugin in Obsidian Desktop or Mobile.

## System Info
OS: iOS 15, MacOS Monterey
Obsidian Version: 1.2.1
Plugin Version: 1.1.1

**Comment by tnichols217** [comment]
Alright, appologies I did not notice that and I bumped the version to 1.1.2 to hopefully fix the issue

Commit: 6be928a6ffbcceef540145a8ffec3e332875ef5a
Version: 1.1.2
