### ISSUE TITLE
[BUG: External] line breaks not working when placed inside an admonition

### ISSUE THREAD

**Issue by nousernameavailableanymore** [tnichols217/obsidian-columns#17]
# Describe the bug
When using Obsidian Columns inside an Admonitions codeblock, the line breaks are not working.

## Steps To Reproduce
1. Have Admonitions plugin installed
2. Create an admonition in a note
3. Put a col/col-md block inside the admonition codeblock
4. Type some text followed by a line break (enter)
5. Type some more text

## Expected behavior
Text after the line break gets put into a new line

## Actual behavior
Text after the line break remains on same line as text before the line break

## Snippet for reproduction
``````
`````ad-note
````col
```col-md
line1
line1
```
```col-md
line1
line2
```
````
`````
``````

## Result
![image](https://user-images.githubusercontent.com/45376324/172027756-be316334-dbba-45f9-aff0-a35a4e22c642.png)

## System Info
Obsidian Version: 0.14.6
Plugin Version: 
- Admonition: 9.0.3 (latest)
- Obsidian Columns 1.1.4 (latest)

**Comment by tnichols217** [comment]
Is this in pive preview or reading mode?

**Comment by tnichols217** [comment]
Using the new syntax works normally:
````
> [!note] a
> ```col
> line1
> line1
> 
> line1
> line1
> ```
````
Also applied a patch for the old syntax in v 1.1.5
