### ISSUE TITLE
[BUG: Internal] Empty additional column

### ISSUE THREAD

**Issue by str-enjo** [tnichols217/obsidian-columns#19]
When using example with syntax
```
!!!col
    (flex-grow)
        (Text in column 1)
    (flex-grow)
        (Text in column 2)
```
from README result is rendered with empty first column

![image](https://user-images.githubusercontent.com/97307533/172045784-50b57bee-864d-40f7-8b54-06096b35cde6.png)
![image](https://user-images.githubusercontent.com/97307533/172045798-616fdcef-cea2-40a0-b097-9efe6f33caf0.png)

OS: Windows 10
Obsidian Version:  v0.14.6
Plugin Version: 1.1.5

**Comment by tnichols217** [comment]
You don't need you put the list notation inside a codeblocks for it to work, just remove the codeblock and it'll work fine.

**Comment by tnichols217** [comment]
For example :
Put 
```
!!!col
    (flex-grow)
        (Text in column 1)
    (flex-grow)
        (Text in column 2)
```

And not 

````md
```col
!!!col
    (flex-grow)
        (Text in column 1)
    (flex-grow)
        (Text in column 2)
```
````
