### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by ngirard** [tnichols217/obsidian-columns#2]
Using latest Obsidian (insider) version on Ubuntu 21.10.

Cheers !

**Comment by ngirard** [comment]
Hey @tnichols217, sorry for the late reply.
The problem is gone with the latest version.
Closing.

**Comment by tnichols217** [comment]
> Hey @tnichols217, sorry for the late reply.
> The problem is gone with the latest version.
> Closing.

Nice! Glad to know
