### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by Missionary2112** [tnichols217/obsidian-columns#21]
# Describe the bug
The content of the second column is turned into Heading of Column 3

## Steps To Reproduce
Steps to reproduce the behavior: Create 2 columns & fill in the contents for each one → see the error

## Expected behavior
The content of second column should stay in second column.

## Screenshots
- Reading mode
![Screenshot - 2022-06-10 18 25 12 (Obsidian)](https://user-images.githubusercontent.com/98799613/173167378-82fd5ed7-e1de-427d-8f3e-7fdd11f59d2c.jpg)
- Preview mode
![Screenshot - 2022-06-10 18 25 25 (Obsidian)](https://user-images.githubusercontent.com/98799613/173167446-09d47298-fae3-4edd-9403-4677aa81f7db.jpg)

## System Info
OS: Monterey 12.4
Obsidian Version: v0.14.15
Plugin Version: 1.1.6

**Comment by tnichols217** [comment]
Each column needs to be wrapped with 
````
```col-md
```
````
So for you it would be 
`````
````col
```col-md
# Heading 1
Text 1
```
```col-md
# Heading 2
Text 2
```
````
`````
