### ISSUE TITLE
[BUG: Internal] Adding bullet point to last column creates new column

### ISSUE THREAD

**Issue by samur-netizen** [tnichols217/obsidian-columns#29]
# Describe the bug
I have two column-block:
````col
```col-md
First Column
- Some Text
```
Second Column
Some Text
````

It renders properly:
![CleanShot 2022-06-23 at 15 39 32](https://user-images.githubusercontent.com/58331037/175313011-9a042a17-3ca0-4cc7-9aed-7d8898d55b17.png)

Now I set Some Text in Second Column as bullet point:
````col
```col-md
First Column
- Some Text
```
Second Column
- Some Text
````

It doesn't render properly. For that bullet point it creates third column:
![CleanShot 2022-06-23 at 15 41 00](https://user-images.githubusercontent.com/58331037/175313305-53dbf2ae-e59b-4159-a456-b3871dcf4e38.png)

## System Info
OS: macOS Monterey
Obsidian Version:  v0.14.15
Plugin Version: v1.1.8

## Additional information or notes
I checked it on default theme and the issue is the same.

**Comment by tnichols217** [comment]
Add a col-md around your second column. If not, since paragraphs and lists are not the same item, you need to group them with a col-md block
For example:
````col
```col-md
First Column
- Some Text
```
```col-md
Second Column
- Some Text
```
````

**Comment by samur-netizen** [comment]
It works thanks! But I have another issue if I want to add hilight for First Column and Second Column. Then the obsidian columns breaks showing error. The code to reproduce error is:
````col
```col-md
==First Column==
- Some Text
```
```col-md
==Second Column==
- Some Text
```
````

**Comment by tnichols217** [comment]
what error exactly?
I get this, but only because i have the dataview plugin enabled, which makes the equals sign an inline operator

![image](https://user-images.githubusercontent.com/62992267/175319719-63ec061d-fbd5-47fe-bca9-30d667243317.png)

**Comment by samur-netizen** [comment]
You're right! It was because od Dataview. I changed its config for Inline Query Prefix and it works like a charm! Thanks!

**Comment by tnichols217** [comment]
Glad I could help!
