### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by Catnap63** [tnichols217/obsidian-columns#30]
# Feature Request
Is there a way to set column width.  

## Details / Ideas / Implementation
So say you have 3 columns and you want the middle column to be wider.

**Comment by tnichols217** [comment]
See examples on README.md

**Comment by tnichols217** [comment]
## col-md
The col-md block has a settings header that is defined as everything above a === delimiter For example, to set the flexGrow value:

```col-md
flexGrow=2
===
MD to be rendered
```
