### ISSUE TITLE
[FR] add commands to palette

### ISSUE THREAD

**Issue by JojoBr0** [tnichols217/obsidian-columns#31]
# Feature Request
It would be a great addition to add the ability to insert a column through the command palette. 

## Details / Ideas / Implementation
My idea is to get a command in the palette to insert the columns automated, perhaps with a UI to set the amount of columns etc, like the implementation of [obsidian admonition](https://github.com/valentine195/obsidian-admonition/blob/3e270e470a316b78b69c5b2711f3aaeb606e9dec/src/main.ts#L201).
More details are written in the [Plugin Docs](https://marcus.se.net/obsidian-plugin-docs/guides/commands)

**Comment by tnichols217** [comment]
Sounds good! I'll work on implementing this in a couple days
