### ISSUE TITLE
[BUG: Internal] Third column allways rendered as code 

### ISSUE THREAD

**Issue by JojoBr0** [tnichols217/obsidian-columns#32]
# **Describe the bug**
It looks like if you put more than two columns in a row the third would be rendered as normal code.

## **Steps To Reproduce**
Use:
`````md
````col
```col-md
# one
```
# two
```
# three
````
`````

Result:
![obsidian_columns_bug](https://user-images.githubusercontent.com/92635650/180425967-2d94d7cb-b485-4116-9f56-94a560b8f1e7.jpg)

## **Expected behavior**
Every column should be normal text with markdown support.

### **System Info**
OS: Windows
Obsidian Version: 0.15.6
Plugin Version: 1.1.8

## **Additional information or notes**
I also found out a little workaround:
If you put ```` ```col-md```` in every **second** header it shows normal:
`````md
````col
```col-md
# one
```
# two
```col-md
# three
````
`````

**Comment by tnichols217** [comment]
You're using incorrect syntax, each column should be wrapped with a col-md codeblock like this:

`````
````col
```col-md
# one
```
```col-md
# two
```
```col-md
# three
````
`````
