### ISSUE TITLE
[BUG: Internal] Slow start up time

### ISSUE THREAD

**Issue by shmuga** [tnichols217/obsidian-columns#33]
# Describe the bug
The plugin contributes to about 25% of the startup time and is an outlier acroos all plugins. 

## Steps To Reproduce
1. Enable debug startup time
2. Start obsidian

## Expected behavior
Is it the my only case or other users have the same overhead on the startup?

## Screenshots
<img width="308" alt="image" src="https://user-images.githubusercontent.com/4268223/184991480-ca8cf10a-a713-4041-a7fc-a1ec541bb2ee.png">

## System Info
OS: macOS Big Sur 11.6.7
Obsidian Version: 0.15.9
Plugin Version: 1.2.0

**Comment by tnichols217** [comment]
When I run the profiler this is what I get:
![image](https://user-images.githubusercontent.com/62992267/185001904-33d77b74-9eb4-43e3-a29d-2c17946d2f64.png)

```
Total plugin setup: 2,613ms
obsidian-plotly: 967ms
obsidian-excalidraw-plugin: 422ms
markdown-attributes: 167ms
dataview: 124ms
obsidian-icon-shortcodes: 111ms
obsidian-full-calendar: 99ms
cm-editor-syntax-highlight-obsidian: 87ms
table-editor-obsidian: 67ms
obsidian-banners: 59ms
music-code-blocks: 54ms
obsidian-open-link-with: 50ms
obsidian-admonition: 49ms
obsidian-git: 48ms
obsidian-kanban: 43ms
obsidian-pandoc: 40ms
markdown-prettifier: 32ms
obsidian-jupyter: 29ms
buttons: 28ms
obsidian-outliner: 24ms
obsidian-style-settings: 20ms
obsidian-molecule-renderer: 20ms
obsidian-external-embed: 16ms
convert-url-to-iframe: 15ms
emoji-shortcodes: 11ms
obsidian-desmos: 11ms
better-word-count: 8ms
calendar: 7ms
obsidian-columns: 6ms
```
And this is the full output from the console, ironically columns was the fastest? Across multiple reloads its consistently between 4 and 6 ms for ms. Maybe check your settings or your settings file (`.obsidian/plugins/obsidian-columns/data.json`) settings from an older version of this plugin may have persisted, but I did write code to only save relevant settings however it won't hurt to check? It might be taking longer on first run, maybe just try reopening Obsidian and seeing what kind of performance you get. I've also tested on a second machine to check if there's any difference but the result is the exact same for me.

I'll keep this issue open for now, until we can find out whats going wrong with yours.

**Comment by tnichols217** [comment]
If you'd read the code, the only thing during startup of the plugin that's actually happening is just 
https://github.com/tnichols217/obsidian-columns/blob/main/main.ts#L75

(which loads the settings from data.json)
and that function is defined inside
https://github.com/tnichols217/obsidian-settings/blob/f1d9f99c6f1e5d22c6e7f4a19624a90e3d4875b8/settings.ts#L64-L74

Maybe this is a runtime issue for MacOS? Maybe try testing on another device and see how it responds

**Comment by tnichols217** [comment]
Marking as closed as issue could not be replicated. Feel free to reopen this issue if the problem persists.
