### ISSUE TITLE
I tried to use this plugin inside Obsidian's built in Callout and it didnt work

### ISSUE THREAD

**Issue by looneyapache** [tnichols217/obsidian-columns#34]
I tried to use this plugin inside Obsidian's built in Callout and it didnt work.
Not sure if it is expected behaviour.

Please help

**Comment by tnichols217** [comment]
Mind sending the markdown you're using?

**Comment by tnichols217** [comment]
For me, 
````md
> ```col
> Column 1
> 
> Column 2
> ```
````
produces:
![image](https://user-images.githubusercontent.com/62992267/192986699-4ad04ecd-76c5-4832-b0e1-6fd03fa920da.png)

**Comment by tnichols217** [comment]
Closing for being unable to reproduce issue and issue going stale.
If the problem persists, do not hesitate to reopen this issue :)
