### ISSUE TITLE
BUG: Code block in a column causes next column to render incorrectly

### ISSUE THREAD

**Issue by KosmosisDire** [tnichols217/obsidian-columns#37]
# Describe the bug
Having a code block in a column causes the column after it to break.

## Steps To Reproduce
1. Open a new note and make three columns. 
2. Add any code block to the first column.
3. Observe that the column after the one with the code block in it doesn't render, but rather shows its source contents as a code block.

## Expected behavior
The column after the one with the code block should render normally.

## Screenshots
![image](https://user-images.githubusercontent.com/39423700/201808983-a8df6a7c-5ddc-4724-85ce-7fa199624bb5.png)

## System Info
OS: Windows 11
Obsidian Version: v1.0.3
Plugin Version: v1.2.0

## Additional information or notes
Here is the markdown from my screenshot:
https://pastebin.com/raw/PhR1vcvf

**Comment by tnichols217** [comment]
When using codeblocks inside codeblocks don't forget to next the backticks (`) so where you put ```cpp you needa add an extra ` to all the enclosing codeblocks. For example:



``````
`````col
````col-md
flexGrow=1
===

>[!info] Column 1

```cpp
this is just a normal codeblock added inside of the column.
```

````
````col-md
flexGrow=1
===

>[!info] Column 2



````

````col-md
flexGrow=1
===

>[!info] Column 3

````
`````
``````

**Comment by tnichols217** [comment]
If this fixed your issue, don't forget to close this!

**Comment by KosmosisDire** [comment]
Ah okay, I didn't know this was a rule, but that makes sense. Thanks!

**Comment by tnichols217** [comment]
Glad i could help!
