### ISSUE TITLE
Columns not displaying as expected [BUG: Internal]

### ISSUE THREAD

**Issue by FootPrintStudio** [tnichols217/obsidian-columns#38]
# Describe the bug
The columns aren't displaying as expected, I have added no new plugins since yesterday when the plugin was working normally. However, for some reason, it no longer works for me when I opened up my project today. Screenshots should make what I say more clear.

## Steps To Reproduce
Unknown, current enabled plugin list is as follows:
- Advanced Tables
- Banners
- Bible Reference
- Excalidraw
- Image Toolkit
- Markdown Formatting Assistant
- Multi-Column Markdown
- **Obsidian Columns**
- Quoth
- Sort & Permute lines
- Tag Wrangler

The settings for the plugin is:
- Minimum width of column: 400
- The default span of an item: 0.75

## Expected behaviour
With the current settings, I should see at least 4 columns in reading mode; however, even notes that I had set up yesterday and which were working yesterday are now only showing in one column.

## Screenshots
![image](https://user-images.githubusercontent.com/82737680/205372512-7fa2c241-4747-4508-b1f3-bcf0b1dbcd1d.png)
![image](https://user-images.githubusercontent.com/82737680/205372761-051ed539-88de-4b3d-8e8e-51cab669a26b.png)

## System Info
OS: Windows 10
Obsidian Version:  v1.0.3
Plugin Version:  v1.30

## Additional information or notes
None.

**Comment by tnichols217** [comment]
I released an update for the plugin just a couple days ago changing the settings for the codeblocks, could you try removing the triple equals (the settings delimiter) from the beginning of your col codeblock. If not I'll look into fixing it asap.

**Comment by FootPrintStudio** [comment]
Unfortunately no change; however, I'm curious why it was working yesterday. If the update came out before then, and it's responsible then it shouldn't have been working yesterday either... Although, I'm not sure if I updated the plugins yesterday or not, but I did this morning when I opened up my vault to start working.

I assume this is what you meant.
![image](https://user-images.githubusercontent.com/82737680/205379288-bd12dcab-1161-4609-80a1-79317af8829d.png)

**Comment by tnichols217** [comment]
Could you have changed one of the settings for obsidian columns? If a particular column is too wide its set to wrap them around vertically instead of side by side to improve readability. Maybe your screen size changed or a setting changed? I'll check this out in the morning as it's 4am for me right now. Also check if any of the columns could be particularly wide for any reason, which would trigger to autowrap

**Comment by FootPrintStudio** [comment]
Figured out where the problem is coming from, had a thought and checked out my mobile app, disabled the plugin on mobile and it's now displaying correctly. It would seem that since the display on the mobile is the smallest, it's using that to determine the wrapping on all devices... But you'd definitely have a better guess as to what is happening there, my knowledge of code is very limited.

**Comment by tnichols217** [comment]
Is the problem fixed? I can't seem to replicate it

**Comment by tnichols217** [comment]
Also, by the way, the col-md block was made just to group multiple items together, and for your usecase isn't necessary since your embeds of other documents aren't multiple items, so a simple
````
```col
![[doc1]]

![[doc2]]

![[doc3]]
```
````
would work without the col-md. Its just a convenience feature that I think youd appreciate

**Comment by FootPrintStudio** [comment]
The problem is no quite fixed, however, it's easily worked around since the course seems to come from using Obsidian Sync on mobile.

**Comment by tnichols217** [comment]
Could you try reducing the minimum width of the column from 400 to like 100 or 200 and try? I can't exactly replicate this issue so I'm not sure how to help, sorry.
