### ISSUE TITLE
[FR] Link names not autoupdating

### ISSUE THREAD

**Issue by chenxin0397** [tnichols217/obsidian-columns#39]
# Feature Request
Brief description of feature wanted
现在我们在 OB 里使用 [[文件名]] 这种格式的链接时，当入链文件的文件名发生变动时，正文中的链接也能同时发生改变，但是在Obsidian Columns插件要求的代码块中，链接内容不会自动发生变化

Now when we use the link in the format of [[file name]] in OB, when the file name of the link file changes, the link in the text can also change at the same time, but in the code block required by the Obsidian Columns plugin , the link content does not automatically change

## Details / Ideas / Implementation
Any additional details or specifics about this feature
![动画111](https://user-images.githubusercontent.com/73974352/205430239-ebd6d3f3-76d8-440d-b775-a9151585c6e6.gif)

**Comment by tnichols217** [comment]
I'm not exactly sure how I can solve this, but once I do, I will work on it

**Comment by tnichols217** [comment]
This should be working in the new callout syntax in v1.4.0, but I am still unsure of how to fix in the regular codeblocks

**Comment by tnichols217** [comment]
I dont believe this feature will be possible with the current Obsidian API, if youd like this, use the callout syntax. Closing for now
