### ISSUE TITLE
Two !!!col cannot be rednered

### ISSUE THREAD

**Issue by emisjerry** [tnichols217/obsidian-columns#4]
Two !!!col cannot be rednered

## Steps to reproduce:
The following text cannot be rendered as required: 
```
- !!!col
	- 1
		111
		222
	- 2
		333
		444

- !!!col
	- 1
		111
		222
	- 2
		333
		444
```

## System Info
OS: Windows 11 
Obsidian Version: 0.14.7
Plugin Version: 1.0.5

**Comment by swehba** [comment]
I inserted your second example, and I too see that it is not working. Should it be inside a code block?

**Comment by emisjerry** [comment]
I know the reason now. Continuous lists seperated by a new line will be treated as a list and every item append a new line.

I inserted a blank line between two lists, it works perfectly. So we must insert a block Markdown between Continuous lists.

Here i insert a `---` between lists:
```

- !!!col
	- 1
		111
		222
	- 2
		333
		444

---

- !!!col
	- 1
		111
		222
	- 2
		333
		444

```

**Comment by tnichols217** [comment]
okay this is a weird bug, if you do the exact same thing but dont put a newline between the two lists, it works, but when you add the line it doesnt? ill be working on this.
