### ISSUE TITLE
the links are not appearing in the graphic view

### ISSUE THREAD

**Issue by Maxvn95** [tnichols217/obsidian-columns#40]
# Describe the bug
Hi, I notice that the links are not appearing in the graphic view when the links are inserted into a column. How to solve this problem ?
![Capture d’écran 2022-12-09 à 09 11 30](https://user-images.githubusercontent.com/89469963/206656199-e74b0773-74ea-495f-8f4d-9ff35b51f3b3.png)

**Comment by tnichols217** [comment]
I cannot seem to find a way to accomplish this with the current obsidian plugin API, however I am working on a large update for obsidian-columns which may solve your issue :]

**Comment by Maxvn95** [comment]
Allright, thank you !

**Comment by ToppDev** [comment]
In the callout syntax the linking in the graph view works

**Comment by HamstringAssassin** [comment]
Heya, Just a heads up, looks like this might not be working for the code block syntax. Something like this...

````col
```col-md
# title

###### Docs
[[document]]
```
````

I did a quick test with the callout syntax and links show up in the graph view that way though. Im using version 1.5.2
