### ISSUE TITLE
Column specific alignment[FR]

### ISSUE THREAD

**Issue by jbagwell27** [tnichols217/obsidian-columns#43]
# Feature Request
Have the option to give a specific column a left/right/center/justify alignment. 

## Details / Ideas / Implementation

An example would result in something like this  
![](https://i.imgur.com/ETFTGRt.png)

**Comment by tnichols217** [comment]
This sounds like a good idea. I think a good implementation would put these options in the col-md codeblock? or do you think it would be better as part of the col settings?

**Comment by jbagwell27** [comment]
Maybe having nested, single columns? There's already an alignment in the
main column block, have a nested single column with that alignment. Maybe
just implementing a full single column header rather than making it multi
with just an empty second section
