### ISSUE TITLE
[BUG: Internal] Embedded images render differently depending on link format

### ISSUE THREAD

**Issue by CodeDok** [tnichols217/obsidian-columns#48]
# Describe the bug
When using embedded images via wikilinks the images are aligned at the top of column. But when you use the markdown link format it shifts the images down.

This happens when using the code notation: 
[image](https://user-images.githubusercontent.com/68912385/224846306-1d93e242-328f-4cd2-b290-fb8d3f9299a0.png)

When using the callout notation it is missaligned (does not start at the top) when using markdownlinks and wikilinks.

Tried with Default, Mado Miniflow and Mado 11 Theme.

## Steps To Reproduce
`````col
```col-md
flexGrow=2
===
> [!summary] **This one uses markdown links**
> Tests 
```
```col-md
flexGrow=1
===
![Maßgeschneidert](Maßgeschneidert.png) <-- Replace with an image in your vault
```
````


````col
```col-md
flexGrow=2
===
> [!summary] This one uses wikilinks
> Tests
```
```col-md
flexGrow=1
===
![[Maßgeschneidert.png]] <-- Replace with an image in your vault
```
`````

## Expected behavior
Images should start at the top of the column

## Screenshots
CSS when using Markdown Link:
![image](https://user-images.githubusercontent.com/68912385/224847278-9fbfc94f-9f80-40bf-ad1e-663cf8e79126.png)

CSS when using Wikilink:
![image](https://user-images.githubusercontent.com/68912385/224847530-d5b34396-76c1-48a8-8f0f-479e96509260.png)

## System Info
OS: Windows 10
Obsidian Version: 1.1.16
Plugin Version: 1.4.0

## Additional information or notes
I'm not sure whether you can modify this or this is provided by the obsidian api. But just as a start wanted to write it somewhere down.

**Comment by tnichols217** [comment]
AFAIK, this misalignment happens whether you use columns or not:

![image](https://github.com/tnichols217/obsidian-columns/assets/62992267/3e83ba03-7232-4a9d-aaeb-c7b1352af870)
(right and top are markdownlinks, left and bottom are wikilinks)

I placed the "aa" there for a context paragraph to see the spacing.

Using the following markdown:
`````md

````col
```col-md
aa
![[loop.png]]
```
```col-md
aa
![loop.png](loop.png)
```
````

aa
![loop.png](loop.png)

aa
![[loop.png]]

`````

Closing issue, as it isnt a problem with this plugin, but with Obsidian
