### ISSUE TITLE
Does this work well on Mobile? Are the columns Responsive and flow one below the other on Mobile?

### ISSUE THREAD

**Issue by ManasMadrecha** [tnichols217/obsidian-columns#5]
Kindly update in the README.

**Comment by tnichols217** [comment]
they do not flow underneath each other on mobile, but they do work as columns normally. Considering adding this as a feature in the future!

**Comment by tnichols217** [comment]
fixed and commited in a51e0733f228113b8ea1381c617691e623b9ccc5
