### ISSUE TITLE
[BUG: Internal] Min Width is not updated according to settings.

### ISSUE THREAD

**Issue by qogoist** [tnichols217/obsidian-columns#50]
# Describe the bug
Settings for min-width and default span are not written to the respective CSS variables.

## Steps To Reproduce
Go to the settings for this plugin. Change either of the settings.

## Expected behavior
The CSS variables "--obsidian-columns-min-width" or "--obsidian-columns-def-span" should change in the ":root" and html.style. However they don't.

## Screenshots
![image](https://user-images.githubusercontent.com/8505237/232168240-9c177c39-e26d-47da-9e77-5de034f750af.png)
![image](https://user-images.githubusercontent.com/8505237/232168301-e50acc2e-b74a-4bf4-aba8-b5c238e36202.png)
![image](https://user-images.githubusercontent.com/8505237/232168342-9b4b3063-8d09-47ae-8816-043f7ace7560.png)

## System Info
OS: Windows 11
Obsidian Version: v1.1.16
Plugin Version: v1.4.0

**Comment by tnichols217** [comment]
They are currently updated on a per element level when rendered through JavaScript, but putting it on the root element is definitely a better idea. If youd like to make a PR id be happy to merge as I'm swamped currently and finding it hard to make time to maintain this extension. I will get around to it eventually though!

**Comment by qogoist** [comment]
Uhm, as far as I can tell there is nothing updated on a per-element basis. But that is just me snooping around the elements in the html inspector.

This is what the element css looks like in the inspector:
![image](https://user-images.githubusercontent.com/8505237/232219496-9dfb7edb-66ee-4db8-9b98-4aed104d2018.png)

**Comment by tnichols217** [comment]
Ahh i didn't notice you were referring to the call-out syntax, because the codeblock syntax is dynamically generated here: https://github.com/tnichols217/obsidian-columns/blob/main/main.ts#L125 

I'm not sure what you mean by never saving, as that's handled by the obsidian-settings submodule

**Comment by tnichols217** [comment]
The saving is defined here:
https://github.com/tnichols217/obsidian-columns/blob/main/main.ts#L281
