### ISSUE TITLE
[BUG: Internal] Callout syntax renders differently than code and list

### ISSUE THREAD

**Issue by ToppDev** [tnichols217/obsidian-columns#51]
# Describe the bug
The callout syntax centers the view and has a different scale for images than the list structure or the codeblock syntax. See screenshot below.

## Steps To Reproduce
Use the code below (3x remove the strings `<REMOVE>` before using. They were only added to get the `'''` working here on GitHub)

```md
# List Structure
- !!!col
	- 1
		![](Assets/Attachments/Placeholder-Male.png)
	- 3
		Mr.
		# John Doe
		⚙️ **Head of Department**
		🏢 [Company Link]()
		📧 john.doe@email.com
		☎️ [+1 23 3 23 2 23](tel:+)
# Callout syntax
> [!col]
> ![](Assets/Attachments/Placeholder-Male.png)
> 
>> [!col-md-3]
>> Mr.
>> # John Doe
>> ⚙️ **Head of Department**
>> 🏢 [Company Link]()
>> 📧 john.doe@email.com
>> ☎️ [+1 23 3 23 2 23](tel:+)
# Codeblock 
````col
```col-md
![](Assets/Attachments/Placeholder-Male.png)
```<REMOVE>

```col-md
flexGrow=3
===
Mr.
# John Doe
⚙️ **Head of Department**
🏢 [Company Link]()
📧 john.doe@email.com
☎️ [+1 23 3 23 2 23](tel:+)
```<REMOVE>
````<REMOVE>
```

## Expected behavior
All 3 types of columns look the same

## Screenshots
<img src="https://user-images.githubusercontent.com/17766093/232229411-ed2e135e-1290-4776-9495-046b2acc8572.png" width="400" />

## System Info
OS: Arch Linux 6.2.10-arch1-1
Obsidian Version: v1.1.16
Plugin Version: v1.4.0

**Comment by tnichols217** [comment]
Not a bug, when using callout syntax, wrapping in col-md callouts is required. Add a `>> [!col-md]` before the image on the codeblock example and it works
