### ISSUE TITLE
[BUG: Internal] Checkboxes in columns not saving state

### ISSUE THREAD

**Issue by Seyeumi** [tnichols217/obsidian-columns#57]
# Describe the bug
When creating columns inside a Callout it will not save the state of checkboxes between sessions

## Steps To Reproduce
Create a collapsible callout, create a column inside it, create a checkbox

## Expected behavior
Should save the state of the checkmark between sessions

## System Info
OS: win11
Obsidian Version: 1.3.5
Plugin Version: 1.5.0

## Additional information or notes
I'd add my entire code but it's a big piece but I can post if needed
I don't think it happens without the callouts so I'm unsure what's exactly happening but I figured maybe you could help

**Comment by tnichols217** [comment]
Since we only render the markdown and not actually edit upon events currently, when wanting to check a checkbox you can use the markdown way of changing the box from [] to [x] in the source. I will be working on a feature in the future to integrate the editing though

**Comment by pinetreemoonlight** [comment]
Would be so great if this would be implemented
