### ISSUE TITLE
[QUESTION] How to add border styles

### ISSUE THREAD

**Issue by mrpotatoes** [tnichols217/obsidian-columns#59]
## Question
Is there a way to add borders to the columns?

## Examples
| Image | Description |
|--------|--------|
| <kbd> <img src="https://github.com/tnichols217/obsidian-columns/assets/1066744/35566c5a-0b1b-48da-ae36-e0a9fdbc75f3" /> </kbd> | **Before**: This if from one of the examples in the `README.md` |
| <kbd> <img src="https://github.com/tnichols217/obsidian-columns/assets/1066744/ccc3e9aa-68b8-4375-abe8-3db5c12cc15d" /> </kbd> | **After**: What I would like to be able to do.  | 

## Sundries
This isn't a feature request as it's just a question but it might even make a good feature in the future. Properties to add a border and colour would be amazing.

**Comment by tnichols217** [comment]
Yeah, we don't have that feature right now, but it would be easy to add

**Comment by mrpotatoes** [comment]
Excellent, thank you for the information
