### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Gabe-Kubiak** [tnichols217/obsidian-columns#65]
Let me just start by thanking you for creating/maintaining this plugin. It has greatly helped with formatting Obsidian and in day to day planning. With that said I was wondering if it would be at all possible to update the documentation for the plugin to further break it down. I personally have used Obsidian for several months and could not get the callout syntax working properly. I was able to use the codeblock syntax and only started looking for alternatives when the linking in codeblocks was broken in tree view and checklists were not updating. Then I realized callouts were a native part of markdown and Obsidian and it clicked how to use your other format. For others like me who stumble on this plugin while learning it can be quite confusing that you're using the codeblocks and callout formats from markdown. I honestly thought you added them in the plugin. I think linking the Callout syntax guide on the obsidian site at (https://help.obsidian.md/Editing+and+formatting/Callouts) and explaining just how that works before launching into what you added would save a lot of newer people time and effort in understanding your documentation. Thanks again for your tool. It is honestly such a big part of my daily workflow.

**Comment by tnichols217** [comment]
Ahh, thank you for the suggestion, will implement soon. And glad that I could have helped you in your workflow
