### ISSUE TITLE
[BUG: Internal]

### ISSUE THREAD

**Issue by 161424** [tnichols217/obsidian-columns#66]
# Describe the bug
The format doesn't seem quite right, it's always one line missing
![image](https://github.com/tnichols217/obsidian-columns/assets/32435360/a38bb908-e1aa-43d5-bb28-76633b48bd14)

## Steps To Reproduce
ctrl+c ctrl+v

## Expected behavior
![image](https://github.com/tnichols217/obsidian-columns/assets/32435360/4845ea46-842a-4fdf-a2af-3c4fd61542c2)

## System Info
OS: win11
Obsidian Version: 1.4.16
Plugin Version: 1.5.2

## Additional information or notes

Not only is this column problematic, but there are also issues with using MCL Multi Column columns
![image](https://github.com/tnichols217/obsidian-columns/assets/32435360/4f4a9cfd-24ff-4d56-8b45-5be76092ef02)

**Comment by tnichols217** [comment]
This is just because using col-md creates a div with a border by default, I can add or create an option to remove this border, but it serves to add a space between columns. You can alternatively put your first column into a col-md as well, or put in a css snippet to disable col-md borders.

**Comment by 161424** [comment]
I tried, it's okay
Why are the empty lines here ineffective
![image](https://github.com/tnichols217/obsidian-columns/assets/32435360/5931375c-b40c-4bc9-819e-ac6b1d64b0a6)
