### ISSUE TITLE
[Not issue] My new video introduced Obsidian Columns plugin

### ISSUE THREAD

**Issue by emisjerry** [tnichols217/obsidian-columns#7]
Hi, i've made a YouTube video introduced your plugin, maybe you would be intrested:

https://youtu.be/3w3hpCisw5w

Thought using Chinese, but English CC subtitle provided.

**Comment by tnichols217** [comment]
Wow! Thank you for covering my plugin!

As usual, if there's any problems or feature requests, Ill be willing to check them out!

**Comment by ham1204** [comment]
Thanks for Column height feature!!!

**Comment by tnichols217** [comment]
Wrong issue, but no probs! If there's any problems with it going forward, feel free to drop another issue on gh
