### ISSUE TITLE
How do you align columns with the main body of the note?

### ISSUE THREAD

**Issue by leethologica** [tnichols217/obsidian-columns#70]
How does one ensure that the columns share the same width as the main body of the note, with the same alignment? As you can see here in the below screenshot, the leftmost column has a larger left margin than the main body does, and the rightmost column has the same issue for its right margin. In other words, I want the columns to be aligned with the main body.

<img width="944" alt="Screen Shot 2024-07-02 at 5 47 27 PM" src="https://github.com/tnichols217/obsidian-columns/assets/35752910/fc06808d-3dfe-4415-8f16-f2ec47011ee1">

**Comment by tnichols217** [comment]
you can set the variable --obsidian-columns-padding to have 0 padding on left/right
