### ISSUE TITLE
admonition block not  working in it

### ISSUE THREAD

**Issue by basekno** [tnichols217/obsidian-columns#9]
# [Describe your issue]
as the title shown 

## Steps to reproduce:
[list steps to reproduce issue]

---
not working:

``````col
````ad-example
title: home
collapse: open
color: 1,200,20
```dataview
list 
from "001" 
limit 120
```
````

````ad-example
title: kanban
collapse: open
```dataview
list 
from "002" 
limit 120
```
````
``````
---

---
works well:

``````col
````ad-example
title: home
collapse: open
color: 1,200,20

test1
````

````ad-example
title: home
collapse: open
color: 1,200,20

dataview notworking
````

``````
---

## System Info
OS:  win 10
Obsidian Version: 0.14.6 
Plugin Version: 1.0.5
admonition version:  9.02

thks

**Comment by tnichols217** [comment]
![image](https://user-images.githubusercontent.com/62992267/166633546-96484cff-10db-434a-ab6c-19423f927787.png)
You need to wrap the items you want to be in columns with the col codeblock
Like:
``````md
`````col
````ad-example
title: home
collapse: open
color: 1,200,20
```dataview
list 
from "001" 
limit 120
```
````

````ad-example
title: kanban
collapse: open
```dataview
list 
from "002" 
limit 120
```
````
`````
``````

**Comment by basekno** [comment]
sorry,my fault.
correctly,  DATAVIEW dataview not working, just not admonition

**Comment by tnichols217** [comment]
ah okay, duplicate of #10
